# Generated by Django 3.0 on 2020-08-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='curr_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
