# Generated by Django 3.0 on 2020-08-10 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_curr_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
