# Generated by Django 3.0 on 2020-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
