# Generated by Django 3.0 on 2020-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200806_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
