# Generated by Django 3.0 on 2020-08-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_saving_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
