# Generated by Django 3.0 on 2020-08-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200810_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.UUIDField(default=62640005955955114002398836161193191695, editable=False),
        ),
    ]
