# Generated by Django 3.0 on 2020-08-07 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200806_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(50.0)]),
        ),
    ]
