# Generated by Django 3.0 on 2020-08-07 18:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200807_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8), size=None)),
                ('withdraw', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8), size=None)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Saving')),
            ],
        ),
    ]
